# Use root/example as user/password credentials
version: '3.1'

services:
  spring:
    image: springio/scaffold
    container_name: scaffold_app_compose
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db

  db:
    image: mysql
    container_name: scaffold_mysql_compose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: scaffold
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql